# Generated by Django 4.1.7 on 2024-08-15 11:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import task_distribution_system.task_distribution_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default=task_distribution_system.task_distribution_app.models.ProjectStatus['CREATED'], max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('busy_days_count', models.PositiveIntegerField(default=0)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), help_text='Enter skills separated with commas', size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('skill_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), help_text='Enter skills separated with commas', size=None)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ALLOCATED', 'ALLOCATED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default=task_distribution_system.task_distribution_app.models.TaskStatus['CREATED'], max_length=200)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default=task_distribution_system.task_distribution_app.models.Priority['LOW'], max_length=200)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_distribution_app.project')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task_distribution_app.resource')),
            ],
            options={
                'unique_together': {('title', 'project')},
            },
        ),
        migrations.CreateModel(
            name='TaskResourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_distribution_app.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource', to='task_distribution_app.resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_distribution_app.task')),
            ],
            options={
                'unique_together': {('project', 'task', 'resource')},
            },
        ),
    ]
